- name: play for creating new file
  hosts: allservers
  tasks: 
    - name: creating a file if it does not exist
      file: 
        path: /tmp/fileansi.txt
        state: touch
        mode: '0777'
     
    - name: creating a directory if it doest not exist
      file: 
        path: /temp/diransi
        state: directory
        mode: '0750'
